---
abstract: 'HTTP Action, Adventure and Excitement'
author:
  - 'Stevan Little <stevan.little@iinteractive.com>'
build_requires:
  HTTP::Headers: 0
  HTTP::Request: 0
  HTTP::Response: 0
  Test::Fatal: 0.003
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300023, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-Headers-ActionPack
requires:
  Carp: 0
  HTTP::Date: 0
  HTTP::Headers::Util: 0
  HTTP::Message: 0
  List::Util: 0
  MIME::Base64: 0
  Module::Runtime: 0
  Scalar::Util: 0
  Sub::Exporter: 0
  Time::Piece: 0
  URI: 0
  URI::Escape: 0
  overload: 0
  parent: 0
  strict: 0
  warnings: 0
version: 0.04
x_authority: cpan:STEVAN
